import Route from '@ember/routing/route';

export default Route.extend({
  model() {
    return [{
      "first_name": "Brade",
      "last_name": "Gernier",
      "email": "bgernier0@nymag.com",
      "gender": "Male"
    }, {
    "first_name": "Phillip",
    "last_name": "Gilliam",
    "email": "pgilliam1@google.fr",
    "gender": "Male"
  }, {
  "first_name": "Jorgan",
    "last_name": "Lindop",
    "email": "jlindop2@shutterfly.com",
    "gender": "Male"
}, {
  "first_name": "Raychel",
    "last_name": "Guiso",
    "email": "rguiso3@examiner.com",
    "gender": "Female"
}, {
  "first_name": "Lorry",
    "last_name": "Vaggers",
    "email": "lvaggers4@sfgate.com",
    "gender": "Male"
}, {
  "first_name": "Baird",
    "last_name": "Scardifeild",
    "email": "bscardifeild5@pen.io",
    "gender": "Male"
}, {
  "first_name": "Iris",
    "last_name": "Van Eeden",
    "email": "ivaneeden6@nytimes.com",
    "gender": "Female"
}, {
  "first_name": "Dolph",
    "last_name": "Alvarado",
    "email": "dalvarado7@jugem.jp",
    "gender": "Male"
}, {
  "first_name": "Janaye",
    "last_name": "Chuter",
    "email": "jchuter8@engadget.com",
    "gender": "Female"
}, {
  "first_name": "Eddie",
    "last_name": "Von Der Empten",
    "email": "evonderempten9@who.int",
    "gender": "Female"
}, {
  "first_name": "Whitaker",
    "last_name": "Paradis",
    "email": "wparadisa@fotki.com",
    "gender": "Male"
}, {
  "first_name": "Derrek",
    "last_name": "Belfitt",
    "email": "dbelfittb@elpais.com",
    "gender": "Male"
}, {
  "first_name": "Nicoli",
    "last_name": "Lehrmann",
    "email": "nlehrmannc@businessweek.com",
    "gender": "Female"
}, {
  "first_name": "Renell",
    "last_name": "Patington",
    "email": "rpatingtond@creativecommons.org",
    "gender": "Female"
}, {
  "first_name": "Bearnard",
    "last_name": "Chue",
    "email": "bchuee@economist.com",
    "gender": "Male"
}, {
  "first_name": "Leonardo",
    "last_name": "Speake",
    "email": "lspeakef@yale.edu",
    "gender": "Male"
}, {
  "first_name": "Milka",
    "last_name": "Speight",
    "email": "mspeightg@sciencedirect.com",
    "gender": "Female"
}, {
  "first_name": "Renado",
    "last_name": "Hitzke",
    "email": "rhitzkeh@rambler.ru",
    "gender": "Male"
}, {
  "first_name": "Manolo",
    "last_name": "Iorizzi",
    "email": "miorizzii@odnoklassniki.ru",
    "gender": "Male"
}, {
  "first_name": "Mohammed",
    "last_name": "Trattles",
    "email": "mtrattlesj@quantcast.com",
    "gender": "Male"
}, {
  "first_name": "Gerhard",
    "last_name": "Brooking",
    "email": "gbrookingk@webmd.com",
    "gender": "Male"
}, {
  "first_name": "Marlin",
    "last_name": "Shenton",
    "email": "mshentonl@cbc.ca",
    "gender": "Male"
}, {
  "first_name": "Lyell",
    "last_name": "Rodolphe",
    "email": "lrodolphem@dell.com",
    "gender": "Male"
}, {
  "first_name": "Barris",
    "last_name": "Fairbard",
    "email": "bfairbardn@nifty.com",
    "gender": "Male"
}, {
  "first_name": "Brewster",
    "last_name": "Spencelayh",
    "email": "bspencelayho@accuweather.com",
    "gender": "Male"
}, {
  "first_name": "Taffy",
    "last_name": "Deane",
    "email": "tdeanep@google.com",
    "gender": "Female"
}, {
  "first_name": "Margalit",
    "last_name": "Bumphries",
    "email": "mbumphriesq@vimeo.com",
    "gender": "Female"
}, {
  "first_name": "Rhoda",
    "last_name": "Husselbee",
    "email": "rhusselbeer@cbc.ca",
    "gender": "Female"
}, {
  "first_name": "Kat",
    "last_name": "Ullock",
    "email": "kullocks@bravesites.com",
    "gender": "Female"
}, {
  "first_name": "Brocky",
    "last_name": "Gallihawk",
    "email": "bgallihawkt@umn.edu",
    "gender": "Male"
}, {
  "first_name": "Hanni",
    "last_name": "Gaddas",
    "email": "hgaddasu@nsw.gov.au",
    "gender": "Female"
}, {
  "first_name": "Kaja",
    "last_name": "Hucks",
    "email": "khucksv@home.pl",
    "gender": "Female"
}, {
  "first_name": "Brooke",
    "last_name": "Ferminger",
    "email": "bfermingerw@altervista.org",
    "gender": "Male"
}, {
  "first_name": "Silvie",
    "last_name": "Dmiterko",
    "email": "sdmiterkox@apple.com",
    "gender": "Female"
}, {
  "first_name": "Kata",
    "last_name": "Treffrey",
    "email": "ktreffreyy@google.com.br",
    "gender": "Female"
}, {
  "first_name": "Avrit",
    "last_name": "Beteriss",
    "email": "abeterissz@nationalgeographic.com",
    "gender": "Female"
}, {
  "first_name": "Sal",
    "last_name": "Ioannou",
    "email": "sioannou10@furl.net",
    "gender": "Male"
}, {
  "first_name": "Laraine",
    "last_name": "Beaven",
    "email": "lbeaven11@businessinsider.com",
    "gender": "Female"
}, {
  "first_name": "Garrik",
    "last_name": "Pelham",
    "email": "gpelham12@si.edu",
    "gender": "Male"
}, {
  "first_name": "Fredric",
    "last_name": "Fray",
    "email": "ffray13@cpanel.net",
    "gender": "Male"
}, {
  "first_name": "Pamelina",
    "last_name": "Hindsberg",
    "email": "phindsberg14@go.com",
    "gender": "Female"
}, {
  "first_name": "Roxy",
    "last_name": "Gerdts",
    "email": "rgerdts15@dion.ne.jp",
    "gender": "Female"
}, {
  "first_name": "Parsifal",
    "last_name": "Brasener",
    "email": "pbrasener16@live.com",
    "gender": "Male"
}, {
  "first_name": "Noell",
    "last_name": "Balle",
    "email": "nballe17@flickr.com",
    "gender": "Female"
}, {
  "first_name": "Lane",
    "last_name": "Quixley",
    "email": "lquixley18@reddit.com",
    "gender": "Female"
}, {
  "first_name": "Rahal",
    "last_name": "Cawker",
    "email": "rcawker19@japanpost.jp",
    "gender": "Female"
}, {
  "first_name": "Ross",
    "last_name": "O'Crotty",
    "email": "rocrotty1a@yelp.com",
    "gender": "Male"
}, {
  "first_name": "Stacey",
    "last_name": "Culley",
    "email": "sculley1b@slashdot.org",
    "gender": "Female"
}, {
  "first_name": "Natalina",
    "last_name": "Durand",
    "email": "ndurand1c@mit.edu",
    "gender": "Female"
}, {
  "first_name": "Sonya",
    "last_name": "Kyngdon",
    "email": "skyngdon1d@scientificamerican.com",
    "gender": "Female"
}];
  }

});
